Repository sony/nnabla-ext-cuda, pull requests merged in 2019-06, with the labels that each got.

#161 Accum BNs properly and fix all-reduce callback bug arise due to accum fix
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
  src/nbla/cuda/cudnn/function/generic/batch_normalization.cu
  src/nbla/cuda/cudnn/function/generic/fused_batch_normalization.cu
Labels: release-note-core

#164 Add ppc64le build support.
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  docker/development/Dockerfile.build-multi-gpu-ppc64le
  docker/development/Dockerfile.build-ppc64le
Labels: release-note-build

#166 Add CUDA implementation of scatter_nd function
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/scatter_nd.hpp
  src/nbla/cuda/function/generic/scatter_nd.cu
Labels: enhancement
