Repository sony/nnabla-ext-cuda, pull requests merged in 2019-07, with the labels that each got.

#168 Fix cuda kernel block calculation for zero size.
  include/nbla/cuda/common.hpp
Labels: release-note-bugfix

#169 LARS (Layer-wise Adaptive Rate Scaling)
  build-tools/code_generator/solver_types.yaml
  include/nbla/cuda/solver/lars.hpp
  src/nbla/cuda/solver/generic/lars.cu
Labels: enhancement

#170 Fix test on ppc64le
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-multi-gpu
  docker/development/Dockerfile.build-multi-gpu-ppc64le
  docker/development/Dockerfile.build-ppc64le
  python/requirements.txt
  python/setup.py
Labels: release-note-build

#172 Add NVTX utilities in Python
  .gitignore
  include/nbla/cuda/nvtx.hpp
  python/setup.py
  python/src/nnabla_ext/cuda/nvtx.pyx
  src/nbla/cuda/CMakeLists.txt
  src/nbla/cuda/nvtx.cpp
Labels: release-note-utility

#173 Add CUDA stream handler class in Python (as an unsupported feature so far)
  include/nbla/cuda/init.hpp
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cuda/init.pyx
  src/nbla/cuda/init.cpp.tmpl
Labels: release-note-utility

#174 Concurrent streams in backward conv & disable nan propagation in MaxPoolingCudnn
  include/nbla/cuda/cuda.hpp
  include/nbla/cuda/cudnn/cudnn.hpp
  include/nbla/cuda/cudnn/function/convolution.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cudnn/cudnn.cpp
  src/nbla/cuda/cudnn/function/generic/convolution.cu
  src/nbla/cuda/cudnn/function/generic/deconvolution.cu
Labels: release-note-op-layer
