Repository sony/nnabla-ext-cuda, pull requests merged in 2019-09, with the labels that each got.

#182 Includes cuda lib in wheel
  CMakeLists.txt
  build-tools/make/build-with-docker.mk
  build-tools/make/options.mk
  build-tools/scripts/nvidia-docker.sh
  python/setup.cfg.build-wheel.in
  python/setup.cfg.in
  python/setup.py
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-build

#180 Add CUDA implementation of OneHot function
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/one_hot.hpp
  src/nbla/cuda/function/generic/one_hot.cu
Labels: release-note-op-layer

#181 Skip allreduce if array is not updated
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
Labels: release-note-utility

#183 Min-max quantization
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/min_max_quantize.hpp
  src/nbla/cuda/function/generic/min_max_quantize.cu
Labels: enhancement
