Repository sony/nnabla-ext-cuda, pull requests merged in 2019-04, with the labels that each got.

#135 [Bug] Image Augmentation
  src/nbla/cuda/function/generic/image_augmentation.cu
Labels: release-note-bugfix

#137 Add CUDA implemention for random_choice function.
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/random_choice.hpp
  src/nbla/cuda/function/generic/random_choice.cu
Labels: enhancement

#136 Add TopKDataCuda and TopKGradCuda function implementations.
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/common.hpp
  include/nbla/cuda/function/top_k_data.hpp
  include/nbla/cuda/function/top_k_grad.hpp
  include/nbla/cuda/utils/bitonic_sort.cuh
  include/nbla/cuda/utils/minmax.cuh
  include/nbla/cuda/utils/top_k.cuh
  include/nbla/cuda/utils/warp_shuffle.cuh
  include/nbla/cuda/utils/warp_vote.cuh
  src/nbla/cuda/function/generic/top_k_data.cu
  src/nbla/cuda/function/generic/top_k_grad.cu
Labels: enhancement

#138 Add tile function (c.f. numpy.tile or torch.repeat)
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/tile.hpp
  src/nbla/cuda/function/generic/tile.cu
Labels: enhancement

#139 Add AdaBound & AMSBound
  build-tools/code_generator/solver_types.yaml
  include/nbla/cuda/solver/adabound.hpp
  include/nbla/cuda/solver/amsbound.hpp
  src/nbla/cuda/solver/generic/adabound.cu
  src/nbla/cuda/solver/generic/amsbound.cu
Labels: release-note-utility

#141 Add numeric include
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
Labels: bug, code-reviewed
