Repository sony/nnabla-ext-cuda, pull requests merged in 2019-05, with the labels that each got.

#144 Fix bugs in min and max functions when used to return indices.
  include/nbla/cuda/function/min.hpp
  include/nbla/cuda/half.hpp
  src/nbla/cuda/array/cuda_array.cu
  src/nbla/cuda/function/generic/max.cu
  src/nbla/cuda/function/generic/mean.cu
  src/nbla/cuda/function/generic/min.cu
Labels: bug

#148 gather_nd and selection by index variable (advanced indexing)
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/gather_nd.hpp
  src/nbla/cuda/function/generic/gather_nd.cu
  src/nbla/cuda/function/generic/slice.cu
Labels: enhancement

#147 Fix compile errors in nbla_cli build
  .gitignore
  src/nbla_cli/CMakeLists.txt
  src/nbla_cli/nbla_cuda.cpp
Labels: release-note-build
