Repository sony/nnabla-ext-cuda, pull requests merged in 2019-10, with the labels that each got.

#184 Update FlipCuda and RandomFlipCuda implementation
  include/nbla/cuda/function/flip.hpp
  src/nbla/cuda/function/generic/flip.cu
  src/nbla/cuda/function/generic/random_flip.cu
Labels: release-note-op-layer

#185 Use thrust async sort and custom make_seqeuence for faster operation.
  include/nbla/cuda/function/sort.hpp
  src/nbla/cuda/function/generic/sort.cu
Labels: release-note-op-layer

#186 Exit with 0 if no tests in pytest
  build-tools/make/build.mk
Labels: release-note-build

#187 Added auto-forward for pycpp
  examples/cpp/mnist_collection/train_dcgan_cuda.cpp
  examples/cpp/mnist_collection/train_lenet_classifier_cuda.cpp
  examples/cpp/mnist_collection/train_resnet_classifier_cuda.cpp
  examples/cpp/mnist_collection/train_siamese_cuda.cpp
  examples/cpp/mnist_collection/train_vae_cuda.cpp
  examples/cpp/mnist_collection/train_vat_cuda.cpp
Labels: code-reviewed

#189 Add DaliIterator
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-multi-gpu
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-multi-gpu
  python/setup.py
  python/src/nnabla_ext/cuda/experimental/__init__.py
  python/src/nnabla_ext/cuda/experimental/_dali_iterator.py
  python/src/nnabla_ext/cuda/experimental/dali_iterator.py
  python/test/conftest.py
  python/test/cuda/test_dali_iterator.py
  python/test/cuda/test_large_blocks.py
Labels: release-note-utility

#188 Fix a race condition when using thrust::async::sort
  src/nbla/cuda/function/generic/sort.cu
Labels: bug, release-note-bugfix
