Repository sony/nnabla-ext-cuda, pull requests merged in 2020-04, with the labels that each got.

#216 Fix type name is not allowed.
  src/nbla/cuda/function/generic/random_erase.cu
Labels: release-note-bugfix

#217 Double Backward for ChannelLast and Half Type
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/function_types_cudnn.yaml
  include/nbla/cuda/cudnn/function/sum_pooling.hpp
  include/nbla/cuda/function/interpolate.hpp
  include/nbla/cuda/utils/nd_index.hpp
  src/nbla/cuda/cudnn/function/generic/sum_pooling.cu
  src/nbla/cuda/function/generic/interpolate.cu
  src/nbla/cuda/function/generic/max_pooling_backward.cu
Labels: release-note-op-layer

#220 Unpooling with Channel Last
  include/nbla/cuda/function/interpolate.hpp
  include/nbla/cuda/function/unpooling.hpp
  src/nbla/cuda/function/generic/unpooling.cu
Labels: release-note-op-layer

#219 Resolve some compiler warnings
  src/nbla/cuda/function/generic/random_crop.cu
  src/nbla/cuda/function/generic/random_erase.cu
Labels: release-note-core
