Repository sony/nnabla-ext-cuda, pull requests merged in 2020-06, with the labels that each got.

#226 Quantize/DequantizeLinear
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/dequantize_linear.hpp
  include/nbla/cuda/function/quantize_linear.hpp
  src/nbla/cuda/function/generic/dequantize_linear.cu
  src/nbla/cuda/function/generic/quantize_linear.cu
Labels: release-note-op-layer

#227 [fix][c++] Allow calling multiple times and catch errors in FFT/IFFT
  include/nbla/cuda/function/fft.hpp
  include/nbla/cuda/function/ifft.hpp
  include/nbla/cuda/function/utils/fft.cuh
  include/nbla/cuda/function/utils/fft.hpp
  src/nbla/cuda/function/generic/fft.cu
  src/nbla/cuda/function/generic/ifft.cu
Labels: release-note-bugfix

#228 Fix brand name
  doc/build/build_distributed.md
  docker/README.md
Labels: release-note-doc
