Repository sony/nnabla-ext-cuda, pull requests merged in 2020-08, with the labels that each got.

#237 Fix the gradient operation when inplaced with output variable.
  src/nbla/cuda/function/generic/scatter_nd.cu
Labels: release-note-bugfix

#240 add watch dog for those might cause dead-waiting functions
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
  include/nbla/cuda/communicator/watch_dog.hpp
  src/nbla/cuda/CMakeLists.txt
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
  src/nbla/cuda/communicator/watch_dog.cpp
  src/nbla/cuda/test/test_watch_dog.cpp
Labels: release-note-utility

#241 Upgrade gcc to 4.9.2
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  src/nbla/cuda/cuda.cpp
Labels: release-note-build

#242 extend the timeout of all_reduce to avoid CI error
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
Labels: release-note-build
