Repository sony/nnabla-ext-cuda, pull requests merged in 2020-05, with the labels that each got.

#222 update devtoolset package version. update url of yum repository
  docker/development/Dockerfile.build
Labels: release-note-build

#223 Interpolation with half_pixel and half_pixel_for_nn
  include/nbla/cuda/function/interpolate.hpp
  src/nbla/cuda/function/generic/interpolate.cu
Labels: release-note-op-layer

#224 Add deconvolution output padding option.
  include/nbla/cuda/cudnn/function/deconvolution.hpp
  include/nbla/cuda/function/deconvolution.hpp
Labels: release-note-op-layer

#225 Add a flag to choose conv algo by a heuristic
  include/nbla/cuda/cudnn/cudnn.hpp
  src/nbla/cuda/cudnn/cudnn.cpp
Labels: release-note-utility
