Repository sony/nnabla-ext-cuda, pull requests merged in 2020-11, with the labels that each got.

#250 BugFix: Index of height and width in the channel-last of RandomErase function
  src/nbla/cuda/function/generic/random_erase.cu
Labels: release-note-bugfix

#251 Build with chocolatey environment.
  build-tools/make/build-with-docker.mk
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
  build-tools/msvc/tools/default_folders.bat
  build-tools/msvc/tools/default_folders_wheel.bat
  build-tools/msvc/tools/default_settings.bat
  build-tools/msvc/tools/env.bat
  build-tools/msvc/tools/get-cudnn-version.py
  doc/build/build_windows.md
  doc/build/quick_build_tools.md
  docker/development/Dockerfile.build
  python/setup.py
Labels: release-note-build

#249 Inplace for unary/binary arithmetic functions
  include/nbla/cuda/function/add_scalar.hpp
  include/nbla/cuda/function/bc_add2.hpp
  include/nbla/cuda/function/div2.hpp
  include/nbla/cuda/function/mul2.hpp
  include/nbla/cuda/function/mul_scalar.hpp
  include/nbla/cuda/function/pow2.hpp
  include/nbla/cuda/function/pow_scalar.hpp
  include/nbla/cuda/function/sub2.hpp
  include/nbla/cuda/function/utils/base_transform_binary.cuh
  include/nbla/cuda/function/utils/base_transform_binary.hpp
  include/nbla/cuda/function/utils/base_transform_unary.cuh
  include/nbla/cuda/function/utils/base_transform_unary.hpp
  src/nbla/cuda/cudnn/function/generic/add2.cu
  src/nbla/cuda/function/generic/div2.cu
  src/nbla/cuda/function/generic/mul2.cu
  src/nbla/cuda/function/generic/pow2.cu
  src/nbla/cuda/function/generic/pow_scalar.cu
  src/nbla/cuda/solver/generic/clip_grad.cuh
Labels: release-note-op-layer

#253 Add cuda implementation of scatter_add function
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/scatter_add.hpp
  src/nbla/cuda/function/generic/scatter_add.cu
Labels: release-note-op-layer

#254 Add Cuda implementation of AdaBelief solver
  build-tools/code_generator/solver_types.yaml
  include/nbla/cuda/solver/adabelief.hpp
  src/nbla/cuda/solver/generic/adabelief.cu
Labels: release-note-op-layer

#255 Norm and NormNormalization
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/norm.hpp
  include/nbla/cuda/function/norm_normalization.hpp
  src/nbla/cuda/function/generic/norm.cu
  src/nbla/cuda/function/generic/norm_normalization.cu
Labels: release-note-op-layer

#257 Separate tf converter from nnabla.
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
Labels: release-note-build

#258 Change libarchive location
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
Labels: release-note-build

#259 update dockerfiles to install nnabla_tf_converter
  build-tools/make/build-with-docker.mk
  docker/py36/cuda100/Dockerfile
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
Labels: release-note-build
