Repository sony/nnabla-ext-cuda, pull requests merged in 2020-02, with the labels that each got.

#204 CUDNN NHWC deconvolution
  include/nbla/cuda/cudnn/function/deconvolution.hpp
  include/nbla/cuda/function/deconvolution.hpp
  src/nbla/cuda/cudnn/function/generic/deconvolution.cu
  src/nbla/cuda/function/generic/deconvolution.cu
Labels: enhancement, release-note-op-layer

#205 Add CUDA implementation of patch_correlation function.
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/patch_correlation.hpp
  src/nbla/cuda/function/generic/patch_correlation.cu
Labels: release-note-op-layer

#206 Enable building CLI with CUDA
  CMakeLists.txt
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  build-tools/make/options.mk
  build-tools/msvc/build_cpplib.bat
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
  build-tools/msvc/tools/default_folders.bat
  build-tools/msvc/tools/default_folders_wheel.bat
  examples/cpp/mnist_collection/CMakeLists.txt
  examples/cpp/mnist_training/CMakeLists.txt
  include/nbla/cuda/defs.hpp
  python/setup.cfg.build-wheel.in
  python/setup.cfg.in
  src/nbla/cuda/CMakeLists.txt
  src/nbla_cli/CMakeLists.txt
Labels: release-note-build
