Repository sony/nnabla-ext-cuda, pull requests merged in 2020-03, with the labels that each got.

#210 Add AddN and MulN functions
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/add_n.hpp
  include/nbla/cuda/function/mul_n.hpp
  include/nbla/cuda/utils/pointers.cuh
  src/nbla/cuda/function/generic/add_n.cu
  src/nbla/cuda/function/generic/mul_n.cu
Labels: release-note-op-layer

#211 Support a deterministic algorithm at cudnnMaxPooling
  include/nbla/cuda/cudnn/function/max_pooling.hpp
Labels: release-note-bugfix

#212 Fix CPU Library name for creating wheel.
  python/setup.cfg.in
Labels: release-note-build

#214 RandomErase Function
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/random_erase.hpp
  include/nbla/cuda/utils/nd_index.cuh
  include/nbla/cuda/utils/random.cuh
  include/nbla/cuda/utils/random.hpp
  src/nbla/cuda/cudnn/cudnn.cpp
  src/nbla/cuda/function/generic/random_erase.cu
  src/nbla/cuda/utils/random.cu
Labels: release-note-op-layer
