Repository sony/nnabla-ext-cuda, pull requests merged in 2020-07, with the labels that each got.

#230 Add licenses and Notice
  CMakeLists.txt
  NOTICE.md
  python/setup.py
  src/nbla/cuda/CMakeLists.txt
  third_party/CMakeLists.txt
  third_party/LICENSES.md
Labels: release-note-doc

#232 Add DLPack interface to share a tensor on host or device among frameworks and libraries without copy
  CMakeLists.txt
  build-tools/make/build-with-docker.mk
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  include/nbla/cuda/array/cuda_array.cuh
  include/nbla/cuda/array/cuda_dlpack_array.hpp
  src/nbla/cuda/array/cuda_dlpack_array.cpp
  src/nbla/cuda/array/cuda_dlpack_array.cu
  src/nbla/cuda/init.cpp.tmpl
  third_party/LICENSES.md
Labels: release-note-utility

#234 Make scatter_nd work in static graph.
  src/nbla/cuda/function/generic/scatter_nd.cu
Labels: release-note-bugfix

#235 Fix Gelu Backward
  src/nbla/cuda/function/generic/gelu.cu
Labels: bug, release-note-bugfix

#236 Disable pytorch installation on python3.5 build.
  build-tools/make/build-with-docker.mk
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
Labels: release-note-build
