Repository sony/nnabla-ext-cuda, pull requests merged in 2021-12, with the labels that each got.

#355 Add linspace function
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/linspace.hpp
  src/nbla/cuda/function/generic/linspace.cu
Labels: release-note-op-layer

#356 Add PYTEST_OPTS for pytest parallel execution
  build-tools/make/build.mk
  build-tools/msvc/test.bat
  python/pytest.ini
Labels: release-note-build

#357 Make ISTFT consistent with PyTorch implementation (NOLA condition)
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  include/nbla/cuda/function/istft.hpp
  include/nbla/cuda/function/kernel/istft.cuh
  include/nbla/cuda/function/stft.hpp
  include/nbla/cuda/function/utils/stft.cuh
  src/nbla/cuda/function/generic/istft.cu
  src/nbla/cuda/function/generic/stft.cu
Labels: release-note-op-layer

#358 Support broadcast in instance norm kernel to improve performance
  include/nbla/cuda/function/instance_normalization.hpp
  include/nbla/cuda/function/kernel/instance_normalization.cuh
  src/nbla/cuda/function/generic/instance_normalization.cu
  src/nbla/cuda/function/generic/layer_normalization.cu
Labels: release-note-op-layer

#359 fix multithread issues
  CMakeLists.txt
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cudnn/init.cpp.tmpl
  src/nbla/cuda/init.cpp.tmpl
Labels: release-note-bugfix

#361 Remove the argument "output_mask" from Dropout
  include/nbla/cuda/function/dropout.hpp
  src/nbla/cuda/function/generic/dropout.cu
Labels: release-note-bugfix

#362 Default disable watchdog and enable it with environment variable
  src/nbla/cuda/communicator/watch_dog.cpp
  src/nbla/cuda/test/test_watch_dog.cpp
Labels: release-note-utility

#360 Remove -U option from pip install in nnabla-ext-cuda
  doc/build/build.md
Labels: release-note-ignore

#364 Use get_current_device_attribute rather than properties
  include/nbla/cuda/common.hpp
  src/nbla/cuda/common.cpp
  src/nbla/cuda/utils/reduce.cu
Labels: release-note-bugfix

#365 Fix spelling "Currently"
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-doc

#363 upgrade g++ from 4.9.2 to 6.5.0 and enable stdc++14
  .gitignore
  CMakeLists.txt
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  examples/cpp/mnist_collection/CMakeLists.txt
  examples/cpp/mnist_collection/GNUmakefile
  examples/cpp/mnist_collection/README.md
  examples/cpp/mnist_training/CMakeLists.txt
  examples/cpp/mnist_training/GNUmakefile
  examples/cpp/mnist_training/README.md
  python/setup.py
  src/nbla/cuda/CMakeLists.txt
  src/nbla_cli/CMakeLists.txt
Labels: release-note-build

#366 Add AssignCuda not to perform host-device copy
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/assign.hpp
  src/nbla/cuda/function/generic/assign.cu
Labels: release-note-bugfix
