Repository sony/nnabla-ext-cuda, pull requests merged in 2021-02, with the labels that each got.

#277 enable multi-thread training
  CMakeLists.txt
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cudnn/function/generic/convolution.cu
  src/nbla/cuda/test/test_multi_process_data_parallel_communicator.cpp
  src/nbla/cuda/test/test_multi_thread_training.cpp
Labels: release-note-bugfix

#278 check gpu compatibility
  build-tools/make/build.mk
  build-tools/scripts/gpu_info.py
  build-tools/scripts/skel/incompatibale_gpu_list.py.tmpl
  build-tools/scripts/update_gpu_list.py
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  python/requirements.txt
  python/setup.py
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cuda/incompatibale_gpu_list.py
  python/src/nnabla_ext/cudnn/__init__.py
Labels: release-note-core

#280 Pad memory optimization and add repeat mode
  src/nbla/cuda/function/generic/pad.cu
Labels: release-note-op-layer

#281 Optimize normalization functions implementation
  build-tools/code_generator/function_types.yaml
  build-tools/code_generator/function_types_cudnn.yaml
  include/nbla/cuda/cudnn/function/batch_normalization.hpp
  include/nbla/cuda/cudnn/function/group_normalization.hpp
  include/nbla/cuda/cudnn/function/instance_normalization.hpp
  include/nbla/cuda/cudnn/function/layer_normalization.hpp
  include/nbla/cuda/cudnn/function/sync_batch_normalization.hpp
  include/nbla/cuda/cudnn/function/tensor_normalization.hpp
  include/nbla/cuda/cudnn/function/weight_standardization.hpp
  include/nbla/cuda/function/batch_normalization.hpp
  include/nbla/cuda/function/group_normalization.hpp
  include/nbla/cuda/function/instance_normalization.hpp
  include/nbla/cuda/function/kernel/batch_normalization.cuh
  include/nbla/cuda/function/layer_normalization.hpp
  include/nbla/cuda/function/sync_batch_normalization.hpp
  include/nbla/cuda/function/tensor_normalization.hpp
  include/nbla/cuda/function/weight_standardization.hpp
  src/nbla/cuda/cudnn/function/generic/batch_normalization.cu
  src/nbla/cuda/cudnn/function/generic/group_normalization.cu
  src/nbla/cuda/cudnn/function/generic/instance_normalization.cu
  src/nbla/cuda/cudnn/function/generic/layer_normalization.cu
  src/nbla/cuda/cudnn/function/generic/tensor_normalization.cu
  src/nbla/cuda/cudnn/function/generic/weight_standardization.cu
  src/nbla/cuda/function/generic/batch_normalization.cu
  src/nbla/cuda/function/generic/group_normalization.cu
  src/nbla/cuda/function/generic/instance_normalization.cu
  src/nbla/cuda/function/generic/kernel/batch_normalization.cu
  src/nbla/cuda/function/generic/layer_normalization.cu
  src/nbla/cuda/function/generic/tensor_normalization.cu
  src/nbla/cuda/function/generic/weight_standardization.cu
Labels: release-note-op-layer

#283 Add cudnn libraries to whl
  python/setup.py
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-build

#282 Memory optimization for STFT/iSTFT
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/istft.hpp
  include/nbla/cuda/function/stft.hpp
  include/nbla/cuda/function/utils/stft.cuh
  include/nbla/cuda/function/utils/stft.hpp
  src/nbla/cuda/function/generic/istft.cu
  src/nbla/cuda/function/generic/stft.cu
Labels: release-note-op-layer

#284 Deformable Convolution
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/deformable_convolution.hpp
  include/nbla/cuda/utils/deformable_im2col.hpp
  src/nbla/cuda/function/generic/deformable_convolution.cu
Labels: release-note-op-layer

#287 Limit numpy version to 1.19.5
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  python/requirements.txt
Labels: release-note-build

#285 Split convolution workspace size
  include/nbla/cuda/cudnn/cudnn.hpp
  src/nbla/cuda/cudnn/cudnn.cpp
  src/nbla/cuda/cudnn/function/generic/convolution.cu
  src/nbla/cuda/cudnn/function/generic/deconvolution.cu
Labels: release-note-op-layer

#288 Fix a bug in LSTM
  src/nbla/cuda/cudnn/function/generic/lstm.cu
Labels: release-note-bugfix
