Repository sony/nnabla-ext-cuda, pull requests merged in 2021-07, with the labels that each got.

#322 Implement module nvml to replace pynvml
  python/requirements.txt
  python/setup.py
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cudnn/__init__.py
Labels: release-note-utility

#323 Higher-order gradients for normalization functions
  include/nbla/cuda/function/spectral_norm.hpp
Labels: release-note-op-layer

#324 Fix multithread cudnn handle sharing problem
  include/nbla/cuda/cuda.hpp
  include/nbla/cuda/cudnn/cudnn.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cudnn/cudnn.cpp
  src/nbla/cuda/test/test_multi_thread_training.cpp
Labels: release-note-bugfix

#327 Re-enable the cudnn convolution metrics caching.
  src/nbla/cuda/cudnn/function/generic/convolution.cu
Labels: release-note-bugfix

#326 Add CUDA implementaion of roi_align function.
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/roi_align.hpp
  include/nbla/cuda/half.hpp
  src/nbla/cuda/function/generic/roi_align.cu
Labels: release-note-core

#328 CI: Support Nvidia Compatible Driver for CUDA11 docker images
  docker/README.md
  docker/release/.bashrc
  docker/release/20-nvidia-cuda-compat.sh
  docker/release/Dockerfile.py36-cuda100
  docker/release/Dockerfile.py36-cuda100-mpi211
  docker/release/Dockerfile.py36-cuda100-mpi316
  docker/release/Dockerfile.py36-cuda102
  docker/release/Dockerfile.py36-cuda102-mpi211
  docker/release/Dockerfile.py36-cuda102-mpi316
  docker/release/Dockerfile.py36-cuda110
  docker/release/Dockerfile.py36-cuda110-mpi211
  docker/release/Dockerfile.py36-cuda110-mpi316
  docker/release/Dockerfile.py37-cuda100
  docker/release/Dockerfile.py37-cuda100-mpi211
  docker/release/Dockerfile.py37-cuda100-mpi316
  docker/release/Dockerfile.py37-cuda102
  docker/release/Dockerfile.py37-cuda102-mpi211
  docker/release/Dockerfile.py37-cuda102-mpi316
  docker/release/Dockerfile.py37-cuda110
  docker/release/Dockerfile.py37-cuda110-mpi211
  docker/release/Dockerfile.py37-cuda110-mpi316
  docker/release/Dockerfile.py38-cuda100
  docker/release/Dockerfile.py38-cuda100-mpi211
  docker/release/Dockerfile.py38-cuda100-mpi316
  docker/release/Dockerfile.py38-cuda102
  docker/release/Dockerfile.py38-cuda102-mpi211
  docker/release/Dockerfile.py38-cuda102-mpi316
  docker/release/Dockerfile.py38-cuda110
  docker/release/Dockerfile.py38-cuda110-mpi211
  docker/release/Dockerfile.py38-cuda110-mpi316
  docker/release/bash.bashrc
  docker/release/cudalibcheck
  docker/release/shinit_v2
Labels: release-note-build

#329 Remove ReLUCudaCudnn
  build-tools/code_generator/function_types_cudnn.yaml
  include/nbla/cuda/common.hpp
  include/nbla/cuda/cudnn/function/relu.hpp
  src/nbla/cuda/cudnn/function/generic/relu.cu
  src/nbla/cuda/function/generic/relu.cu
Labels: release-note-core
