Repository sony/nnabla-ext-cuda, pull requests merged in 2021-08, with the labels that each got.

#331 Boolean Indexing Functions
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/bool_fill.hpp
  include/nbla/cuda/function/bool_gather.hpp
  include/nbla/cuda/function/bool_scatter.hpp
  include/nbla/cuda/function/utils/bool_indexing.cuh
  src/nbla/cuda/function/generic/bool_fill.cu
  src/nbla/cuda/function/generic/bool_gather.cu
  src/nbla/cuda/function/generic/bool_scatter.cu
  src/nbla/cuda/function/generic/broadcast.cu
Labels: release-note-op-layer

#332 Fix APT_OPTS for runtime dockerfiles
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
Labels: release-note-build

#333 Optimize SyncBatchNorm
  include/nbla/cuda/cudnn/function/sync_batch_normalization.hpp
  include/nbla/cuda/function/kernel/sync_batch_normalization.cuh
  include/nbla/cuda/function/sync_batch_normalization.hpp
  src/nbla/cuda/cudnn/function/generic/sync_batch_normalization.cu
  src/nbla/cuda/function/generic/kernel/sync_batch_normalization.cu
  src/nbla/cuda/function/generic/sync_batch_normalization.cu
  third_party/LICENSES.md
Labels: release-note-op-layer

#334 ignore label less 0 to support segmentation boundary
  src/nbla/cuda/function/generic/categorical_cross_entropy.cu
  src/nbla/cuda/function/generic/softmax_cross_entropy.cu
Labels: release-note-bugfix

#335 Support p=0 for dropout function
  include/nbla/cuda/function/dropout.hpp
Labels: release-note-op-layer

#336 Make inplace option in most of Function operations obsolete
  include/nbla/cuda/cudnn/function/relu.hpp
  include/nbla/cuda/function/add_scalar.hpp
  include/nbla/cuda/function/bc_add2.hpp
  include/nbla/cuda/function/mul_scalar.hpp
  include/nbla/cuda/function/sub2.hpp
  src/nbla/cuda/cudnn/function/generic/add2.cu
  src/nbla/cuda/function/generic/leaky_relu.cu
  src/nbla/cuda/function/generic/random_erase.cu
  src/nbla/cuda/function/generic/relu.cu
Labels: release-note-break-compat

#337 Install nnabla_converter to py38 docker images
  docker/release/Dockerfile.py38-cuda100-mpi211
  docker/release/Dockerfile.py38-cuda100-mpi316
  docker/release/Dockerfile.py38-cuda102-mpi211
  docker/release/Dockerfile.py38-cuda102-mpi316
  docker/release/Dockerfile.py38-cuda110-mpi211
  docker/release/Dockerfile.py38-cuda110-mpi316
Labels: release-note-build
