Repository sony/nnabla-ext-cuda, pull requests merged in 2021-11, with the labels that each got.

#347 Add pytest-xdist options
  build-tools/make/build.mk
  build-tools/msvc/test.bat
  python/pytest.ini
  python/requirements.txt
Labels: release-note-build

#348 eliminate code warning
  src/nbla/cuda/cudnn/function/generic/convolution.cu
Labels: release-note-ignore

#350 update auto format
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
  src/nbla/cuda/cudnn/function/generic/batch_normalization.cu
  src/nbla/cuda/cudnn/function/generic/fused_batch_normalization.cu
  src/nbla/cuda/function/generic/batch_normalization.cu
  src/nbla/cuda/function/generic/cumprod.cu
Labels: release-note-ignore

#351 Revert "replace centos with ubuntu"
  build-tools/make/build-with-docker.mk
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
Labels: release-note-build

#352 Need explicit Shape_t initialization since CUDA 11.1
  src/nbla/cuda/function/generic/group_normalization.cu
Labels: release-note-bugfix

#354 Optimize CumProd/CumSum
  include/nbla/cuda/function/cumprod.hpp
  include/nbla/cuda/function/cumsum.hpp
  include/nbla/cuda/function/kernel/cumprod.cuh
  include/nbla/cuda/utils/atomic_min.cuh
  include/nbla/cuda/utils/scan.cuh
  include/nbla/cuda/utils/scan_ops/base.cuh
  include/nbla/cuda/utils/scan_ops/prod.cuh
  include/nbla/cuda/utils/scan_ops/sum.cuh
  include/nbla/cuda/utils/scan_setup.hpp
  include/nbla/cuda/utils/types.cuh
  python/test/cuda/function/refs.py
  python/test/cuda/function/test_cumprod_backward_cuda_kernel.py
  python/test/cuda/function/test_scan_cuda_kernel.py
  src/nbla/cuda/function/generic/cumprod.cu
  src/nbla/cuda/function/generic/cumsum.cu
  src/nbla/cuda/function/generic/kernel/cumprod.cu
  src/nbla/cuda/utils/scan_setup.cu
Labels: release-note-op-layer

#353 support python3.9
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  docker/release/Dockerfile.py39-cuda100
  docker/release/Dockerfile.py39-cuda100-mpi211
  docker/release/Dockerfile.py39-cuda100-mpi316
  docker/release/Dockerfile.py39-cuda102
  docker/release/Dockerfile.py39-cuda102-mpi211
  docker/release/Dockerfile.py39-cuda102-mpi316
  docker/release/Dockerfile.py39-cuda110
  docker/release/Dockerfile.py39-cuda110-mpi211
  docker/release/Dockerfile.py39-cuda110-mpi316
Labels: release-note-build
