Repository sony/nnabla-ext-cuda, pull requests merged in 2021-03, with the labels that each got.

#289 Memory optimization for SpectralNorm
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/spectral_norm.hpp
  src/nbla/cuda/function/generic/spectral_norm.cu
Labels: release-note-op-layer

#290 Higher-order Gradients
  src/nbla/cuda/function/generic/max_pooling_backward.cu
Labels: release-note-core

#291 fix key error of checking GPU
  build-tools/scripts/update_gpu_list.py
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cuda/incompatible_gpu_list.py
  python/src/nnabla_ext/cudnn/__init__.py
Labels: release-note-bugfix

#292 Load bias grad only if convolution has bias.
  src/nbla/cuda/cudnn/function/generic/convolution.cu
  src/nbla/cuda/cudnn/function/generic/deconvolution.cu
Labels: release-note-bugfix

#293 fix: solve the error that pynvml cannot solve the path to nvml.dll on windows
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cudnn/__init__.py
Labels: release-note-bugfix

#295 Fix numerical instability for log_sigmoid and softplus
  src/nbla/cuda/function/generic/log_sigmoid.cu
  src/nbla/cuda/function/generic/softplus.cu
Labels: release-note-bugfix
