Repository sony/nnabla-ext-cuda, pull requests merged in 2021-06, with the labels that each got.

#314 version-up of cuda and python
  docker/tutorial/Dockerfile
Labels: release-note-build

#315 add the support of copyright check
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
Labels: release-note-build

#317 fix: pynvml.nvml has no attribute nvml_lib
  python/src/nnabla_ext/cuda/__init__.py
  python/src/nnabla_ext/cudnn/__init__.py
Labels: release-note-utility

#318 fix duplicated entry of function_types.yaml
  build-tools/code_generator/function_types.yaml
Labels: release-note-bugfix

#319 Allow additional options to commands that use network
  build-tools/make/build.mk
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  docker/py36/cuda100/Dockerfile
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
  docker/py38/cuda100/Dockerfile
  docker/py38/cuda100/mpi2.1.1/Dockerfile
  docker/py38/cuda100/mpi3.1.6/Dockerfile
  docker/py38/cuda102/Dockerfile
  docker/py38/cuda102/mpi2.1.1/Dockerfile
  docker/py38/cuda102/mpi3.1.6/Dockerfile
  docker/py38/cuda110/Dockerfile
  docker/py38/cuda110/mpi2.1.1/Dockerfile
  docker/py38/cuda110/mpi3.1.6/Dockerfile
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
  docker/tutorial/Dockerfile
  python/requirements.txt
  third_party/CMakeLists.txt
Labels: release-note-build

#320 install flatbuffer compiler for new tflite converter
  docker/py36/cuda100/Dockerfile
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
Labels: release-note-bugfix
