Repository sony/nnabla-ext-cuda, pull requests merged in 2021-04, with the labels that each got.

#296 fix conv segment fault error
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
Labels: release-note-bugfix

#297 remove conda
  CMakeLists.txt
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/test.bat
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  docker/py36/cuda100/Dockerfile
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
  docker/py38/cuda100/Dockerfile
  docker/py38/cuda100/mpi2.1.1/Dockerfile
  docker/py38/cuda100/mpi3.1.6/Dockerfile
  docker/py38/cuda102/Dockerfile
  docker/py38/cuda102/mpi2.1.1/Dockerfile
  docker/py38/cuda102/mpi3.1.6/Dockerfile
  docker/py38/cuda110/Dockerfile
  docker/py38/cuda110/mpi2.1.1/Dockerfile
  docker/py38/cuda110/mpi3.1.6/Dockerfile
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-build

#298 Change workspace limit dtype from int to int64_t
  include/nbla/cuda/cudnn/cudnn.hpp
  src/nbla/cuda/cudnn/cudnn.cpp
Labels: release-note-bugfix

#300 fused binary operator
  include/nbla/cuda/function/utils/base_transform_binary.cuh
  include/nbla/cuda/function/utils/base_transform_binary.hpp
Labels: release-note-op-layer

#301 limit h5py version to 3.1.0
  python/requirements.txt
Labels: release-note-ignore

#302 set h5py version <= 3.1.0
  python/requirements.txt
Labels: release-note-ignore

#305 fix curl not found error
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
Labels: release-note-ignore

#304 Searchsorted and Meshgrid implementation
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/meshgrid.hpp
  include/nbla/cuda/function/searchsorted.hpp
  src/nbla/cuda/function/generic/meshgrid.cu
  src/nbla/cuda/function/generic/searchsorted.cu
Labels: release-note-op-layer

#307 Use urllib instead of requests
  build-tools/scripts/update_gpu_list.py
  python/requirements.txt
Labels: release-note-utility

#308 Modify SoftPlus to accept beta argument
  include/nbla/cuda/function/softplus.hpp
  src/nbla/cuda/function/generic/softplus.cu
Labels: release-note-op-layer
