Repository sony/nnabla-ext-cuda, pull requests merged in 2021-01, with the labels that each got.

#267 add NNabla version arg for dockerfile
  docker/py36/cuda100/Dockerfile
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
  docker/py38/cuda100/Dockerfile
  docker/py38/cuda100/mpi2.1.1/Dockerfile
  docker/py38/cuda100/mpi3.1.6/Dockerfile
  docker/py38/cuda102/Dockerfile
  docker/py38/cuda102/mpi2.1.1/Dockerfile
  docker/py38/cuda102/mpi3.1.6/Dockerfile
  docker/py38/cuda110/Dockerfile
  docker/py38/cuda110/mpi2.1.1/Dockerfile
  docker/py38/cuda110/mpi3.1.6/Dockerfile
Labels: release-note-ignore

#270 update GNUmakefile in example/cpp
  examples/cpp/mnist_collection/GNUmakefile
  examples/cpp/mnist_collection/README.md
  examples/cpp/mnist_training/GNUmakefile
  examples/cpp/mnist_training/README.md
Labels: release-note-bugfix

#271 add code to implement asymmetric watch dog
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
Labels: release-note-bugfix

#272 Fix failed to compile nnabla cuda wheel.
  python/setup.py
Labels: release-note-build

#273 fix: solve the nccl error while running more than 2 gpus
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/py36/cuda100/mpi2.1.1/Dockerfile
  docker/py36/cuda100/mpi3.1.6/Dockerfile
  docker/py36/cuda102/mpi2.1.1/Dockerfile
  docker/py36/cuda102/mpi3.1.6/Dockerfile
  docker/py36/cuda110/mpi2.1.1/Dockerfile
  docker/py36/cuda110/mpi3.1.6/Dockerfile
  docker/py37/cuda100/mpi2.1.1/Dockerfile
  docker/py37/cuda100/mpi3.1.6/Dockerfile
  docker/py37/cuda102/mpi2.1.1/Dockerfile
  docker/py37/cuda102/mpi3.1.6/Dockerfile
  docker/py37/cuda110/mpi2.1.1/Dockerfile
  docker/py37/cuda110/mpi3.1.6/Dockerfile
  docker/py38/cuda100/mpi2.1.1/Dockerfile
  docker/py38/cuda100/mpi3.1.6/Dockerfile
  docker/py38/cuda102/mpi2.1.1/Dockerfile
  docker/py38/cuda102/mpi3.1.6/Dockerfile
  docker/py38/cuda110/mpi2.1.1/Dockerfile
  docker/py38/cuda110/mpi3.1.6/Dockerfile
  docker/runtime/Dockerfile.runtime-mpi
Labels: release-note-bugfix

#274 fix: solve the bug that no found CUDNN_PATH while building in windows
  build-tools/msvc/tools/env.bat
  build-tools/msvc/tools/get-cudnn-version.py
Labels: release-note-build
