Repository sony/nnabla-ext-cuda, pull requests merged in 2022-04, with the labels that each got.

#391 Fix: copy function was missing in MaxPoolingCudnn
  include/nbla/cuda/cudnn/function/max_pooling.hpp
Labels: release-note-bugfix

#393 update document for build windows with vs2019
  doc/build/build_windows.md
Labels: release-note-ignore

#394 upgrade default version from python 3.6 to python 3.7
  build-tools/msvc/build_cpplib.bat
Labels: release-note-ignore

#395 Fix: Slow Softmax backward when H and W are 1
  include/nbla/cuda/cudnn/cudnn.hpp
  src/nbla/cuda/cudnn/cudnn.cpp
Labels: release-note-bugfix

#396 simplify nvtx code and update copyright
  include/nbla/cuda/nvtx.hpp
  python/src/nnabla_ext/cuda/nvtx.pyx
  python/test/cuda/nvtx/nvtx-check.py
  python/test/cuda/nvtx/test_nvtx.py
  src/nbla/cuda/nvtx.cpp
Labels: release-note-ignore

#397 Fix flatc build issue
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-build
