Repository sony/nnabla-ext-cuda, pull requests merged in 2022-03, with the labels that each got.

#380 restrict condition with dst for communicator reduce
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
Labels: release-note-core

#382 Replace pow to products
  build-tools/msvc/build_cpplib.bat
  include/nbla/cuda/function/kernel/sync_batch_normalization.cuh
  src/nbla/cuda/function/generic/norm.cu
  src/nbla/cuda/function/generic/norm_normalization.cu
Labels: release-note-build

#381 caching device properties for avoiding slow recall
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/test/test_cached_device_prop.cpp
  src/nbla/cuda/utils/reduce.cu
  third_party/CMakeLists.txt
Labels: release-note-utility

#383 Not to use deprecated .dtype() in DALI to remove warning messages
  python/src/nnabla_ext/cuda/experimental/_dali_iterator.py
Labels: release-note-ignore

#384 Speedup SortCuda with cub::DeviceSegmentedRadixSort
  CMakeLists.txt
  include/nbla/cuda/function/sort.hpp
  src/nbla/cuda/function/generic/sort.cu
  third_party/CMakeLists.txt
  third_party/LICENSES.md
Labels: release-note-op-layer

#385 Enable customizing std types and functions with memory allocation
  examples/cpp/mnist_collection/train_dcgan_cuda.cpp
  examples/cpp/mnist_collection/train_lenet_classifier_cuda.cpp
  examples/cpp/mnist_collection/train_resnet_classifier_cuda.cpp
  examples/cpp/mnist_collection/train_siamese_cuda.cpp
  examples/cpp/mnist_collection/train_vae_cuda.cpp
  examples/cpp/mnist_collection/train_vat_cuda.cpp
  examples/cpp/mnist_training/main.cpp
  src/nbla/cuda/function/generic/pack_padded_sequence.cu
  src/nbla/cuda/function/generic/pad_packed_sequence.cu
Labels: release-note-core

#386 Support NVTX range events
  docker/development/Dockerfile.build
  include/nbla/cuda/nvtx.hpp
  python/src/nnabla_ext/cuda/nvtx.pyx
  python/test/cuda/nvtx/nvtx-check.py
  python/test/cuda/nvtx/test_nvtx.py
  src/nbla/cuda/init.cpp.tmpl
  src/nbla/cuda/nvtx.cpp
Labels: release-note-utility

#387 Improve docker entrypoint set
  docker/release/.entrypoint-cuda-mpi.sh
  docker/release/.entrypoint-cuda.sh
Labels: release-note-ignore

#389 Auto restart DALI iterator at StopIteration
  python/src/nnabla_ext/cuda/experimental/_dali_iterator.py
Labels: release-note-utility

#390 Feature/20210608 cholesky decomposition
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/common.hpp
  include/nbla/cuda/cuda.hpp
  include/nbla/cuda/cusolver.hpp
  include/nbla/cuda/function/batch_cholesky.hpp
  include/nbla/cuda/math.hpp
  src/nbla/cuda/CMakeLists.txt
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cusolver.cpp
  src/nbla/cuda/function/generic/batch_cholesky.cu
Labels: release-note-op-layer
