Repository sony/nnabla-ext-cuda, pull requests merged in 2022-12, with the labels that each got.

#443 fix segmentation fault issue on docker container
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-bugfix

#445 build python from pyenv
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.cuda-cudnn-lib-in-wheel-test
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
Labels: release-note-build

#448 Options to scale gradients and to keep dtype in allreduce callback
  build-tools/make/build.mk
  include/nbla/cuda/communicator/dl_nccl.h.tmpl
  include/nbla/cuda/communicator/multi_process_data_parallel_communicator.hpp
  src/nbla/cuda/communicator/multi_process_data_parallel_communicator.cu
Labels: release-note-core

#447 fix namespace packages for wheel to pass twine check
  python/setup.py
  python/src/nnabla_ext/__init__.py
Labels: release-note-build

#446 set windows all-in-one path automatically when import
  build-tools/msvc/tools/env.bat
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-bugfix
