Repository sony/nnabla-ext-cuda, pull requests merged in 2022-11, with the labels that each got.

#436 help to generate final nvtx file to avoid unnecessary failure
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.cuda-cudnn-lib-in-wheel-test
  python/test/cuda/nvtx/test_nvtx.py
Labels: release-note-ignore

#437 support python3.10
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  python/requirements.txt
  python/src/nnabla_ext/cuda/__init__.py
Labels: release-note-build

#438 Fix cython build failure by missing cutensor.h in non-docker env
  CMakeLists.txt
  build-tools/msvc/build_wheel.bat
  build-tools/msvc/tools/get_cutensor.bat
  python/setup.cfg.build-wheel.in
  python/setup.py
  src/nbla/cuda/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: release-note-bugfix

#439 Use not cast but get in nan/inf check
  src/nbla/cuda/solver/generic/mixed_precision_training.cuh
Labels: release-note-bugfix

#440 complete setup cfg in all condition
  python/setup.cfg.in
Labels: release-note-bugfix

#441 change pip installation method
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-build

#442 add python310 into lib_in_wheel
  docker/development/Dockerfile.cuda-cudnn-lib-in-wheel-test
Labels: release-note-build
