Repository sony/nnabla-ext-cuda, pull requests merged in 2022-10, with the labels that each got.

#429 Use a singleton function for cudaGetDeviceProperties to avoid slowdown
  include/nbla/cuda/common.hpp
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/cudnn/function/generic/fused_batch_normalization.cu
  src/nbla/cuda/function/generic/depthwise_convolution.cu
  src/nbla/cuda/function/generic/depthwise_deconvolution.cu
  src/nbla/cuda/function/generic/transpose.cu
Labels: release-note-bugfix

#430 Caching cuTENSOR handles and optimize TranposeCuda::setup_impl
  include/nbla/cuda/cuda.hpp
  src/nbla/cuda/cuda.cpp
  src/nbla/cuda/function/generic/transpose.cu
Labels: release-note-core

#431 Faster LayerNormCuda::setup_impl (GN and IN as well) by removing unnecessary function creation
  src/nbla/cuda/cudnn/function/generic/instance_normalization.cu
  src/nbla/cuda/function/generic/group_normalization.cu
  src/nbla/cuda/function/generic/instance_normalization.cu
  src/nbla/cuda/function/generic/layer_normalization.cu
Labels: release-note-op-layer

#432 Fix release docker image build
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-ignore

#433 Add ca-certificates to Dockerfiles
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.cuda-cudnn-lib-in-wheel-test
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
  docker/runtime/Dockerfile.runtime
  docker/runtime/Dockerfile.runtime-mpi
  docker/runtime/Dockerfile.runtime-ppc64le
Labels: release-note-build

#434 Not to all-reduce gradients of beta and gamma in sync BN
  .gitignore
  src/nbla/cuda/function/generic/sync_batch_normalization.cu
Labels: release-note-bugfix

#435 add watchdog timeout env so that can set timeout
  include/nbla/cuda/communicator/watch_dog.hpp
  src/nbla/cuda/communicator/watch_dog.cpp
  src/nbla/cuda/test/test_watch_dog.cpp
Labels: release-note-utility
