Repository sony/nnabla-ext-cuda, pull requests merged in 2022-09, with the labels that each got.

#420 Add narrow function for NdArray
  include/nbla/cuda/array/cuda_array.hpp
  include/nbla/cuda/array/cuda_dlpack_array.hpp
  python/src/nnabla_ext/cuda/experimental/_dali_iterator.py
  src/nbla/cuda/array/cuda_array.cpp
  src/nbla/cuda/array/cuda_dlpack_array.cpp
Labels: release-note-core

#421 Error function (erf) implementation (CUDA)
  build-tools/code_generator/function_types.yaml
  include/nbla/cuda/function/erf.hpp
  include/nbla/cuda/half.hpp
  src/nbla/cuda/function/generic/erf.cu
Labels: release-note-op-layer

#422 add example of infer semantic segmentation by cpp
  examples/cpp/semantic_infer/CMakeLists.txt
  examples/cpp/semantic_infer/GNUmakefile
  examples/cpp/semantic_infer/README.md
  examples/cpp/semantic_infer/semantic.cpp
Labels: release-note-examples

#423 Support compile nnabla-ext-cuda with cuTENSOR in non-docker environment
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-mpi
  docker/development/Dockerfile.build-mpi-ppc64le
  docker/development/Dockerfile.build-ppc64le
  src/nbla/cuda/CMakeLists.txt
  third_party/CMakeLists.txt
Labels: release-note-bugfix

#424 fix to create dummy package for multigpu nnabla-ext-cuda
  build-tools/make/build.mk
  python/obsolete/setup.py
  python/obsolete/src/_version.py
Labels: release-note-ignore

#425 Remove unnecessary flatbuffer build
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-ignore

#426 remove obsolete targz rules
  build-tools/make/build-with-docker.mk
  build-tools/make/build.mk
  build-tools/make/options.mk
  docker/development/Dockerfile.build
  docker/development/Dockerfile.build-ppc64le
  python/obsolete/MANIFEST.in
  python/obsolete/pyproject.toml
  python/obsolete/setup.py
  python/obsolete/src/_version.py
Labels: release-note-ignore

#427 Add TopK support to ONNX importer
  include/nbla/cuda/function/top_k_data.hpp
  include/nbla/cuda/utils/top_k.cuh
  src/nbla/cuda/function/generic/top_k_data.cu
Labels: release-note-op-layer

#428 remove duplicate ext-cuda test
  build-tools/make/build.mk
Labels: release-note-ignore
