Repository sony/nnabla-ext-cuda, pull requests merged in 2023-02, with the labels that each got.

#454 fix segmentation fault issue on docker container
  docker/release/Dockerfile.cuda
  docker/release/Dockerfile.cuda-mpi
Labels: release-note-ignore

#455 CUDA11.6 Support
  include/nbla/cuda/defs.hpp
  src/nbla/cuda/function/generic/sort.cu
Labels: release-note-build

#457 Fix SyncBatchnormalizationCuda in channel last mode
  src/nbla/cuda/function/generic/sync_batch_normalization.cu
Labels: release-note-bugfix

#458 Fix to run tests for CUDA functions and solvers
  build-tools/make/build.mk
Labels: release-note-bugfix

#459 update windows document
  doc/build/build_windows.md
  doc/build/quick_build_tools.md
Labels: release-note-ignore
